[package]
name = "fig_log"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
homepage = "https://fig.io"
publish = false

[features]
default = []
console = ["console-subscriber"]

[dependencies]
anyhow = "1.0.58"
console-subscriber = { version = "0.1.6", optional = true, features = ["parking_lot"] }
fig_directories = { path = "../fig_directories" }
once_cell = "1.12.0"
tracing = "0.1.35"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.10", features = ["env-filter", "parking_lot"] }
