[package]
name = "fig_proto"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
homepage = "https://fig.io"
publish = false

[dependencies]
anyhow = "1.0.58"
bytes = "1.1.0"
once_cell = "1.12.0"
prost = "0.10.4"
prost-reflect = { version = "0.8.1", features = ["serde", "derive"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
thiserror = "1.0.30"

[target.'cfg(unix)'.dependencies]
nix = "0.24.1"

[build-dependencies]
prost-reflect-build = "0.8.1"
