[package]
name = "fig_desktop"
version = "2.0.0-alpha.21"
authors = ["fig developers"]
edition = "2021"
rust-version = "1.57"
description = "Fig adds IDE-style autocomplete to your existing terminal"
homepage = "https://fig.io"
publish = false
default-run = "fig_desktop"

[build-dependencies]
image = "0.24.2"

[dependencies]
anyhow = "1.0.57"
base64 = "0.13.0"
bytes = "1.1.0"
camino = "1.0.9"
cfg-if = "1.0.0"
clap = "3.2.5"
dashmap = "5.3.4"
fig_auth = { path = "../rust-lib/fig_auth" }
fig_directories = { path = "../rust-lib/fig_directories" }
fig_install = { path = "../rust-lib/fig_install" }
fig_integrations = { path = "../rust-lib/fig_integrations" }
fig_ipc = { path = "../rust-lib/fig_ipc" }
fig_log = { path = "../rust-lib/fig_log" }
fig_proto = { path = "../rust-lib/fig_proto" }
fig_settings = { path = "../rust-lib/fig_settings" }
fig_telemetry = { path = "../rust-lib/fig_telemetry" }
fig_util = { path = "../rust-lib/fig_util" }
fnv = "1.0.7"
hashbrown = "0.12.0"
image = "0.24.2"
moka = "0.8.5"
once_cell = "1.12.0"
parking_lot = "0.12.1"
percent-encoding = "2.1.0"
regex = "1.5.6"
semver = "1.0.10"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
shellexpand = "2.1.0"
sysinfo = "0.24.3"
system_socket = { path = "../rust-lib/system_socket" }
tokio = { version = "1", features = [ "full" ] }
tracing = "0.1.35"
url = "2.2.2"
whoami = "1.2.1"
wry = { version = "0.18.2", default-features = false, features = ["tray", "protocol", "devtools", "transparent"] }

[target.'cfg(windows)'.dependencies.windows]
version = "0.37.0"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Networking_WinSock",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_System_Console",
    "Win32_System_Ole",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Accessibility",
]

[target.'cfg(target_os="linux")'.dependencies]
freedesktop-icons = "0.2.1"
gtk = { version = "0.15", features = [ "v3_22" ] }
x11rb = "0.10.1"
