[package]
name = "fig_util"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
description = "A layer between the terminal and shell."
homepage = "https://fig.io"
publish = false

[dependencies]
cfg-if = "1.0.0"
clap = { version = "3.2.4", features = ["derive"] }
fig_directories = { path = "../fig_directories" }
serde = "1.0.136"
sha2 = "0.10.2"
thiserror = "1.0.30"
tokio = { version = "1", features = ["process"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.10.1"

[target.'cfg(unix)'.dependencies]
nix = "0.24.1"
