[package]
name = "fig_ipc"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
homepage = "https://fig.io"
publish = false

[dependencies]
anyhow = "1.0.58"
bytes = "1.1.0"
cfg-if = "1.0.0"
fig_proto = { path = "../fig_proto" }
prost = "0.10.4"
prost-reflect = "0.8.1"
system_socket = { path = "../system_socket" }
thiserror = "1.0.30"
tokio = { version = "1.19.2", features = ["fs", "time", "io-util", "net"] }
tracing = "0.1.35"
whoami = "1.2.1"
wsl = "0.1.0"
