[package]
name = "system_socket"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
homepage = "https://fig.io"
publish = false

[dependencies]
pin-project = "1.0.10"
tokio = { version = "1.19.1", features = ["fs", "time", "io-util", "net"] }

[target.'cfg(windows)'.dependencies]
uds_windows = "1.0.2"
