[package]
name = "fig_integrations"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.58"
cfg-if = "1.0.0"
clap = { version = "3.2.5", features = ["derive"] }
fig_directories = { path = "../fig_directories" }
fig_util = { path = "../fig_util" }
regex = "1.5.6"
serde = { version = "1.0.137", features = ["derive"] }
thiserror = "1.0.31"
time = "0.3.10"

